### PR TITLE
Tiers -> master

### PR DESCRIPTION
**Pull request by tomsmeding**
Stuff looks reasonable now, have conducted minimal testing.
Might want to test stuff before actually merging @lieuwex ?

### CODE REVIEW

**Comment by tomsmeding** [comment]
Again, might need more testing before merge; on the other hand, MERGE.

**Comment by lieuwex** [comment]
LGTM
Merge after some testing?

**Comment by tomsmeding** [comment]
I want this so merging now

**Comment by lieuwex** [comment]
HYPE

**Pull request merged**
