### PR TITLE
About time nil gets merged

### PR DESCRIPTION
**Pull request by tomsmeding**
@lieuwex you done testing, you think this is ready for merging?

### CODE REVIEW

**Comment by lieuwex** [comment]
Looks good for merge

**Comment by tomsmeding** [comment]
Whoever's gonna merge this, good luck merging bot.cpp (if you want it before tomorrow, you gotta merge it yourself :P)

**Comment by lieuwex** [comment]
@tomsmeding It was hard in the beginning, but after that I realised it was easiest to checkout the statement switch from master and work up from there. :)

**Comment by tomsmeding** [comment]
HYPE

**Pull request merged**
